version: "3"

services:
  server:
    build: .
    ports:
      - "50051:50051"
    container_name: server
    command: bash -c "go run server/server.go"
    depends_on:
      - mysql
    volumes:
      - ./api:/go/api

  client:
    build: .
    container_name: client
    command: bash -c "go run client/client.go"
    depends_on:
      - server
    volumes:
      - ./api/:/go/api
    ports:
      - "8080:8080"
    
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_grpc
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/my.cnf:/etc/mysql/conf.d/my.con
    ports:
      - "3306:3306"
